#include "common.h"

// Define the entity states array
entity_state_t entity_states[STATE_MAX] = {
        {STATE_NONE, STATE_NONE, 60, SPRITE_STATE_NONE},
        {STATE_PLAYER_STAND0, STATE_PLAYER_STAND0, 30, SPRITE_STATE_PLAYER_STAND0},
        {STATE_PLAYER_MOVE0, STATE_PLAYER_MOVE1, 20, SPRITE_STATE_PLAYER_MOVE0},
        {STATE_PLAYER_MOVE1, STATE_PLAYER_MOVE2, 20, SPRITE_STATE_PLAYER_STAND0},
        {STATE_PLAYER_MOVE2, STATE_PLAYER_MOVE3, 20, SPRITE_STATE_PLAYER_MOVE1},
        {STATE_PLAYER_MOVE3, STATE_PLAYER_MOVE0, 20, SPRITE_STATE_PLAYER_STAND0},
        {STATE_PLAYER_ATTACK0, STATE_PLAYER_ATTACK1, 10, SPRITE_STATE_PLAYER_ATTACK0},
        {STATE_PLAYER_ATTACK1, STATE_PLAYER_ATTACK2, 10, SPRITE_STATE_PLAYER_ATTACK1},
        {STATE_PLAYER_ATTACK2, STATE_PLAYER_ATTACK0, 20, SPRITE_STATE_PLAYER_ATTACK2},
        {STATE_CURSOR0, STATE_CURSOR0, 60, SPRITE_STATE_CURSOR0},
        {STATE_MONSTER_STAND0, STATE_MONSTER_STAND0, 60, SPRITE_STATE_MONSTER_STAND0}
};
